---
title: "Visualização de dados"
author: "Nome"
date: '2022-10-19'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = '',
                      message = FALSE,
                      warning = FALSE)
```

# Construção de gráfico com o ggplot2

Os pacotes utilizados para construção de gráficos.

```{r}
library(tidyverse)
```

## Gráfico de dispersão
<!-- comentário -->

```{r}
mtcars |> 
  ggplot() +
  aes(x=disp,y=mpg) +
  geom_point(size = 3,
             color = 'blue') +
  labs(x = 'Displacement',
       y = 'Miles/gallon',
       title = 'Gráfico 1') +
  theme_minimal() + # troca a cor de fundo
  theme(plot.title = element_text(hjust=0.5,
                                  size = 20),
        axis.text = element_text(size = 20),
        axis.title = element_text(size = 20))
```

# Gráfico de barras

```{r}
mtcars |> 
  ggplot() + 
  aes(x = as.factor(am)) +
  geom_bar(color = 'yellow', 
           fill = 'yellow') +
  scale_x_discrete(labels = 
                    c('Automático', 'Manual'))
```

# Histograma

```{r}
mtcars |> 
  ggplot() +
  aes(x = mpg) +
  geom_histogram(bins = 10, 
                 fill = 'yellow',
                 color = 'black')
```

# Box-plot

- Uma variável

```{r}
mtcars |> 
  ggplot() +
  aes(x = mpg) +
  geom_boxplot()
```
- Duas variáveis: quantitativa e qualitativa
```{r}
mtcars |> 
  ggplot() +
  aes(x = as.factor(am), y = mpg) +
  geom_boxplot()
```

# Gráfico de linhas
```{r}
economics |> 
  ggplot() +
  aes(x = date, y = pop) +
  geom_line()
```






