---
title: "Teste de hipótese para comparação de dois grupos"
author: "Nome"
date: '2022-11-09'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = '',
                      message = FALSE)
```

# Amostras independentes

**Objetivo**: verificar se existe diferença significativa na altura (cm) dos alunos das turmas do primeiro e segundo semestre da Engenharia de Produção.

```{r}
as1 <- c(170,167,173,184,168,190,177,177,162,183,164,162,
         188,181,180,176,180,170,179,176,153,181)
as2 <- c(171,176,180,185,191,187,180,180,176,182,164,
         178,178,163,170,183)
altura <- c(as1,as2)
semestre <- c(rep('S1',length(as1)),
             rep('S2',length(as2)))
dados <- data.frame(semestre,altura)
```

Para visualizar o comportamento dos dados, temos o seguinte box-plot
```{r}
library(ggplot2)
dados |> 
  ggplot() +
  aes(x=semestre, y=altura) +
  geom_boxplot()
```


Fazendo um teste de Shapiro-Wilks, temos

```{r}
library(tidyverse)
altura_s1 <- dados |> 
  filter(semestre=='S1')
shapiro.test(altura_s1$altura)
```

```{r}
altura_s2 <- dados |> 
  filter(semestre=='S2')
shapiro.test(altura_s2$altura)
```

```{r}
t.test(altura~semestre, var.equal=FALSE, 
       data = dados)


wilcox.test(altura~semestre, 
       data = dados)

```

# Amostras dependentes









