---
title: "Instruções do Trabalho &#128221;"
author: ""
date: ""
output: 
  html_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = '',
                      message = FALSE)
```

```{css, echo=FALSE}
h1.title {
  color: rgb(47, 169, 133);
  text-align: center;
}
```

# Objetivo do trabalho

Os alunos deverão elaborar um resumo expandido conforme o template disponibilizado no moodle, cujo o objetivo é fazer uma análise estatística de um conjunto de dados, de preferência da sua área de pesquisa. 

<!--
- Fazer uma análise estatística de um conjunto de dados, de preferência da sua área de pesquisa.
-->

<!--
utilizando o *software* R ou outro recurso computacional. Outros pacotes também podem ser utilizados.
-->

<br>

# Entrega do resumo expandido

- Na sétima e oitava semana: escolher o tema. Elaborar as hipóteses. Planejar a coleta de dados.

- Na nona e décima semana: desenvolvimento e finalização do trabalho.

- Utilizar o template do trabalho disponível no moodle.

- Prazo final de entrega: às 23:59 do dia 12/12.

<br>

# Conjunto de dados

Para selecionar um conjunto de dados:

- Escolher um assunto, de preferência da sua área de pesquisa.

- Caso não tenha um conjunto de dados, opções de *site* com base dados estão disponíveis no moodle.

<br>

# Auxílio computacional

- A análise pode ser feita utilizando o *software* `Jamovi`.

- Outros *softwares* podem ser utilizados, caso o *software* `Jamovi` não tenha os recursos necessário para análise.


<br>

# Avaliação

A nota do trabalho corresponde a **10 pontos**.

O trabalho deverá ser escrito em linguagem científica, objetiva e impessoal, com referências formatadas segundo as normas da ABNT.

A avaliação será de acordo com os seguintes itens:

- (0,5) **Estrutura do trabalho (template)**: o trabalho deve obedecer rigorosamente à estrutura e formatação do template fornecido.

- (1,5) **Apresentação geral e escrita científica**: texto bem escrito, coeso, com linguagem científica e objetiva. Figuras e tabelas devidamente ajustadas e referenciadas no texto.

- (0,5) **Introdução**: apresentar o tema e sua relevância, objetivos claros e fundamentação teórica com referências adequadas.

- (1,5) **Descrição dos dados e variáveis**: descrever de forma clara a origem dos dados e as variáveis envolvidas. Indicar se o estudo é experimental ou observacional.

- (4,0) **Método estatístico**: descrição e aplicação correta do método estatístico escolhido, incluindo as ferramentas computacionais utilizadas. Este é o item de maior peso.

- (1,5) **Intepretação dos resultados**: interpretação coerente e crítica dos resultados obtidos, relacionando-os à literatura ou à prática da engenharia ambiental.

- (0,5) **Conclusão**: síntese dos principais achados e contribuições do estudo, indicando possíveis limitações ou perspectivas futuras..

<br>
**Observações**: 

- Trabalho que  seja uma **cópia de análise** da *internet* será avaliado como zero. 
- **Trabalho mal feito** será avaliado como zero. 
- Trabalho no qual o turnitin identificar **mais de 25%** de similaridade será avaliado como zero.
- Textos gerados total ou parcialmente por ferramentas de inteligência artificial (IA) **serão penalizados**, podendo resultar em **desconto de até 5,0 pontos na nota final**, conforme a gravidade e o grau de dependência da ferramenta.

<br>

# Considerações finais

- Utilizar códigos disponível na *internet* será permitido. Entretanto, a escrita da análise deve ser de autoria do próprio aluno e citar a referência.

- Discutir com os colegas sobre a forma de fazer uma análise será permitido. Entretanto, a escrita da análise deve ser de autoria do próprio aluno.

