---
title: "Instruções do Trabalho &#128221;"
author: ""
date: ""
output: 
  html_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      comment = '',
                      message = FALSE)
```

```{css, echo=FALSE}
h1.title {
  color: rgb(47, 169, 133);
  text-align: center;
}
```

# Objetivo do trabalho

- Fazer uma análise estatística de um conjunto de dados, de preferência da sua área de pesquisa.

- A análise deve ser feita utilizando o *software* `R`.

- Utilizar o modelo do trabalho disponível na pasta do moodle.

- Não há necessidade de uma capa.

<!--
utilizando o *software* R ou outro recurso computacional. Outros pacotes também podem ser utilizados.
-->

<br>

# Prazo de entrega

- Três semanas (19/10 a 08/11) para escolher o conjunto de dados.

- Quatro semanas (09/11 a 06/12) para fazer o resumo.

- Uma semana (07/12 a 14/12) para finalizar o resumo.

- Prazo final de entrega: às 18:20 do dia 14/12.

<br>

# Conjunto de dados

Para selecionar um conjunto de dados:

- Escolher um assunto, de preferência da sua área de pesquisa.

- Caso não tenha um conjunto de dados, opções de *site* com base dados estão disponíveis no moodle.

<br>

# Avaliação

A nota do trabalho corresponde a **10 pontos**.

A avaliação será de acordo com os seguintes itens:

- em construção...


<br>
**Observações**: 

- **Cópias de análise exploratória** da *internet* serão avaliadas como zero. 
- **Trabalhos mal feitos** serão avaliados como zero. 

<br>

# Considerações finais

- Utilizar códigos para reproduzir uma análise exploratória será permitido. Entretanto, a escrita da análise deve ser de autoria do próprio aluno e citar a referência sempre que necessário.

- Discutir com o colega sobre a forma de fazer uma análise exploratória será permitido. Entretanto, a escrita da análise deve ser de autoria do próprio aluno.

